platforms:
  git:
    github:
      enabled: true
      needAuth: true
      owner: aFlyBird0
    gitlab:
      enabled: false
  community:
    feishu:
      enabled: true
users:
  - git:
      github: aFlyBird0
    community:
      feishu: feishu-aFlyBird0
  - git:
      github: github-user-2
#      gitlab: gitlab-user-2 # define a wrong user to test git platform register check
    community:
      feishu: feishu-user-2
  - git:
      github: github-user-3
    community:
      feishu: feishu-user-3
  - git:
      github: github-user-4
    community:
      feishu: feishu-user-4
repos:
  - platform: github
    name: cr-bot-test
    groups:
      feishu: feishu-group-1
    admins:
      - aFlyBird0
    users:
      - github-user-3
      - github-user-4